### ISSUE TITLE
[건의사항] pr에 난이도와 문제를 푼 플랫폼도 Label로 넣는 건 어떤가요?

### ISSUE THREAD

**Issue by areumsheep** [Mirim-Study/Algorithm#221]
![image](https://user-images.githubusercontent.com/48716298/102795013-830f6100-43ef-11eb-823f-5ea457fd5c2f.png)
저희는 [단국대학교 알고리즘 스터디](https://github.com/DKU-STUDY/Algorithm)를 기반으로 돌아가고 있는데 스터디에 재밌는 게 도입이 된 것 같아 저희도 적용해보는 건 어떨까요? 의견이 궁금합니다!

**Comment by pppeum62** [comment]
깔끔하고 괜찮네요👍

**Comment by yoojinhee03** [comment]
좋은것 같아용

**Comment by dayomi02** [comment]
좋아요~

**Comment by areumsheep** [comment]
작업해서 다시 알려드릴게요~ 의견 감사합니다
